# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: npm
    directory: /node
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@types/node"
        versions: [">=15.0.0"]
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: daily
