name: Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: make ci.artifact

    - uses: actions/upload-artifact@v2
      with:
        name: function.zip
        path: ${{ github.workspace }}/build.function/

    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: ${{ github.workspace }}/build.function/
        GHR_COMPRESS: zip
