name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: [stable]
        node-version: ['12', '10']
        cache_counter: [1]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    # https://github.com/jetli/wasm-pack-action
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    # alternative:
    # - name: Install wasm-pack
    #   run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.cache_counter }}-${{ hashFiles('**/Cargo.toml', '**/src/lib.rs') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ matrix.cache_counter }}-

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Test (rust)
      run: make test

    - name: Build (CI)
      run: make ci

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-lint-${{ hashFiles('**/Cargo.toml', '**/src/lib.rs') }}
        restore-keys: |
          ${{ runner.os }}-lint-

    - run: make ci.compliance
