name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust: [stable]
        node-version: ['14', '12', '10']

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    # https://github.com/jetli/wasm-pack-action
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    # alternative:
    # - name: Install wasm-pack
    #   run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: make test
    - run: make ci

  checks:
    name: Checks for fmt, clippy, and docs
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: rust

    - run: make ci.checks
