# https://github.com/ahmadnassri/action-dependabot-auto-merge
name: Dependabot Auto Merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          github-token: ${{ secrets.mytoken }}
