# https://github.com/ahmadnassri/action-dependabot-auto-merge
name: Dependabot Auto Merge

on:
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
  # could and should work, at least for public repos;
  # tracking issue for this action's issue:
  # https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60
  pull_request_target:
    types: [labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-20.04
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: patch
          # Note: This needs to be a PAT with (public) repo rights,
          #       PAT-owning user needs to have write access to this repo
          #       (dependabot needs to recognize the comment as coming from an allowed reviewer)
          github-token: ${{ secrets.BOT_TOKEN }}
